modules/supplier/models/ThingsToDo.php
<?php

namespace app\modules\supplier\models;

use Yii;
use yii\helpers\FileHelper;
use yii\imagine\Image;
use Imagine\Image\Box;
use Imagine\Image\Point;
use yii\helpers\Html;
use yii\helpers\Url;
/**
 * This is the model class for table "things_to_do".
 *
 * @property int $id
 * @property int $offer_id
 * @property string $title
 * @property string $highlights
 * @property string $description
 * @property string $price
 * @property int $begin_date
 * @property int $end_date
 *
 * @property Offer $offer
 */
class ThingsToDo extends \yii\db\ActiveRecord
{
    public $imageFile;
    const WIDTH = 730;
    const HEIGHT = 332;
    const PREFIX = "things_";
    
    public $date_range;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'things_to_do';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['date_range', 'validateDateRange','skipOnEmpty' => false],
            [['title'], 'required'],
            //[['begin_date', 'end_date'], 'integer'],
            [['highlights', 'description'], 'string'],
            [['price'], 'number'],
            [['title'], 'string', 'max' => 255],
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'jpg'],
            //[['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offer::className(), 'targetAttribute' => ['offer_id' => 'id']],
        ];
    }
    
    
    
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        //create a new image considering each prefix
        
        $imageFile = $this->imageFile;
        if(!empty($imageFile)){
            // open image
            $imageFileOpened = Image::getImagine()->open($imageFile->tempName);
            //delete old images
            $this->deleteImage();

            //saving resized image
            $path = Yii::getAlias('@things') . self::PREFIX . md5($this->id) . '.' . $imageFile->getExtension();

            
            $quality = 100;
            
            $imageFileOpened->thumbnail(new Box(self::WIDTH, self::HEIGHT),
             \Imagine\Image\ImageInterface::THUMBNAIL_OUTBOUND)
            ->save($path, ['quality' => $quality]);

        }
        
        
    }
    
    public function afterDelete()
    {
        parent::afterDelete();
        $this->deleteImage();

    }
    
    public function getImageURL()
    {
        return \yii\helpers\Url::base() . '/images/things/' . self::PREFIX . md5($this->id) . '.jpg';
    }


    public function deleteImage()
    {
        //find image by prefix and delete it
        $oldImages = FileHelper::findFiles(Yii::getAlias('@things'), [
            'only' => [
                self::PREFIX . md5($this->id) . '.*',
            ], 
        ]);
        for ($i = 0; $i != count($oldImages); $i++) {
            @unlink($oldImages[$i]);
        }

    }
    
    public function validateDateRange($attribute, $params)
    {
        
        if(empty($this->end_date) or empty($this->begin_date)){
            
            $this->addError($attribute, Yii::t('app', 'Date Range cannot be blank.'));
            
        }
        
    }
    
    public function setDates()
    {
        $dates = explode(" - ", $this->date_range);
        
        $this->begin_date = strtotime($dates[0]);
        $this->end_date = strtotime($dates[1]);
        
    }
    
    public function setDateRange()
    {
        $this->date_range = date('Y-m-d', $this->begin_date) . " - " . date('Y-m-d', $this->end_date);
    }
    
    public function setReadableDateRange()
    {
        $this->begin_date = date('Y-m-d', $this->begin_date);
        $this->end_date = date('Y-m-d', $this->end_date);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'offer_id' => Yii::t('app', 'Offer ID'),
            'title' => Yii::t('app', 'Title'),
            'highlights' => Yii::t('app', 'Highlights'),
            'description' => Yii::t('app', 'Description'),
            'price' => Yii::t('app', 'Price'),
            'begin_date' => Yii::t('app', 'Begin Date'),
            'end_date' => Yii::t('app', 'End Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(Offer::className(), ['id' => 'offer_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActivityThingsToDos()
    {
        return $this->hasMany(ActivityThingsToDo::className(), ['things_to_do_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActivities()
    {
        return $this->hasMany(Activity::className(), ['id' => 'activity_id'])->viaTable('activity_things_to_do', ['things_to_do_id' => 'id']);
    }

}

modules/supplier/controllers/ThingstodoController.php
<?php

namespace app\modules\supplier\controllers;

use Yii;
use app\modules\supplier\models\ThingsToDo;
use app\modules\supplier\models\ThingsToDoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ThingstodoController implements the CRUD actions for ThingsToDo model.
 */
class ThingstodoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ThingsToDo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ThingsToDoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ThingsToDo model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ThingsToDo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
//    public function actionCreate()
//    {
//        $model = new ThingsToDo();
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        }
//
//        return $this->render('create', [
//            'model' => $model,
//        ]);
//    }

    /**
     * Updates an existing ThingsToDo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->setReadableDateRange();
        if ($model->load(Yii::$app->request->post()) ){
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            
            $model->setDates();
            if($model->save()){
                return $this->redirect(['offer/view', 'id' => $model->offer->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ThingsToDo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ThingsToDo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ThingsToDo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ThingsToDo::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/supplier/views/thingstodo/_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\daterange\DateRangePicker;

/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\ThingsToDo */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="things-to-do-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    
    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'highlights')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'imageFile')->fileInput() ?>

   <?php  
    if($model->isNewRecord){
       echo $form->field($model, 'date_range', [
            'addon'=>['prepend'=>['content'=>'<i class="glyphicon glyphicon-calendar"></i>']],
            'options'=>['class'=>'drp-container form-group']
        ])->widget(DateRangePicker::classname(), [
            'useWithAddon'=>true
        ]); 
    }else{
        echo '<label class="control-label" for="offer-date_range">Date Range</label>';
        echo DateRangePicker::widget([
            'model'=>$model,
            'attribute' => 'date_range',
            //'useWithAddon'=>true,
            'convertFormat'=>true,
            'startAttribute' => 'begin_date',
            'endAttribute' => 'end_date',
            'pluginOptions'=>[
                'locale'=>['format' => 'Y-m-d'],
            ]
        ]);
    }
   ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/supplier/views/thingstodo/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\ThingsToDoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="things-to-do-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'offer_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'highlights') ?>

    <?= $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'begin_date') ?>

    <?php // echo $form->field($model, 'end_date') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/supplier/views/thingstodo/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\ThingsToDo */

$this->title = Yii::t('app', 'Create Things To Do');
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Things To Dos'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="things-to-do-create">

    

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/supplier/views/thingstodo/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\modules\supplier\models\ThingsToDoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Things To Dos');
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="things-to-do-index">

    
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'summary' => false,
        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],


            'title',
            [
                'class' => 'yii\grid\DataColumn',
                'format' => 'html',
                'attribute' => 'ImageFile',
                'content' => function($data){ 
                    $image = $data->getImageURL();
                    
                    return Html::img($image,['class'=>'img img-responsive']); 
                    
                },
            ],
            'price:currency',
            'begin_date:date',
            'end_date:date',

            [
                'class' => 'yii\grid\ActionColumn',
                //'template' => '{view}{edit}{delete}',
                'buttons' => [
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                'title' => Yii::t('app', 'lead-delete'),
                        ],['data-method' => 'post']);
                    }
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'delete') {
                        $url = Url::to(['offer/delete-things-to-do','id' => $model->id]);
                        return $url;
                    }
                    if ($action === 'view') {
                        $url = Url::to(['thingstodo/view','id' => $model->id]);
                        return $url;
                    }
                    if ($action === 'update') {
                        $url = Url::to(['thingstodo/update','id' => $model->id]);
                        return $url;
                    }
                }
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

modules/supplier/views/thingstodo/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\ThingsToDo */

$this->title = Yii::t('app', 'Update Things To Do: {nameAttribute}', [
    'nameAttribute' => $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Things To Dos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="things-to-do-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/supplier/views/thingstodo/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\ThingsToDo */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Things To Dos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="things-to-do-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'offer_id',
                'value' => Html::a($model->offer->title,['offer/view','id'=>$model->offer->id]),
                'format' => 'html'
            ],
            'title',
            'highlights:ntext',
            'description:ntext',
            'price',
            'begin_date',
            'end_date',
        ],
    ]) ?>

</div>