modules/supplier/models/Offer.php
<?php

namespace app\modules\supplier\models;

use Yii;
use app\modules\admin\models\BoardBasis;
use app\models\User;
use app\models\Preference;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
/**
 * This is the model class for table "offer".
 *
 * @property int $id
 * @property int $user_id
 * @property int $board_basis_id
 * @property int $preference_id
 * @property string $title
 * @property string $price
 * @property string $location
 * @property double $longitude
 * @property double $latitude
 * @property int $departure_date
 * @property int $return_date
 * @property string $transfer
 * @property string $return_transfer
 * @property string $luggage_allowance
 * @property string $out_link
 * @property int $created_at
 * @property int $updated_at
 * @property int $status
 * @property string $description
 *
 * @property BoardBasis $boardBasis
 * @property User $user
 * @property OfferImage[] $offerImages
 * @property Room[] $rooms
 * @property ThingsToDo[] $thingsToDos
 */
class Offer extends \yii\db\ActiveRecord
{
    const STATUS_RESERVE = 1;
    const STATUS_CALL = 2;
    
    public function updateStatus($status)
    {
        if($status == self::STATUS_RESERVE){
            $this->status = self::STATUS_RESERVE;
        }elseif ($status == self::STATUS_CALL) {
            $this->status = self::STATUS_CALL;
        }
        return $this->update();
    }
    
    public $date_range;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'offer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //['date_range', 'validateDateRange','skipOnEmpty' => false],
            ['date_range','safe'],
            [['departure_date','return_date'], 'default','value'=>0],
            [['title', 'price','board_basis_id'], 'required'],
            [['board_basis_id', 'departure_date', 'return_date', 'created_at', 'status'], 'integer'],
            [['price', 'longitude', 'latitude'], 'number'],
            [['title', 'location', 'transfer', 'return_transfer', 'luggage_allowance', 'out_link'], 'string', 'max' => 255],
            ['description','string'],
            //[['board_basis_id'], 'exist', 'skipOnError' => true, 'targetClass' => BoardBasis::className(), 'targetAttribute' => ['board_basis_id' => 'id']],
            //[['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }
    
    public function validateDateRange($attribute, $params)
    {
        
        if(empty($this->return_date) or empty($this->departure_date)){
            
            $this->addError($attribute, Yii::t('app', 'Date Range cannot be blank.'));
            
        }
        
    }
    
    public function setDates()
    {
        if($this->date_range){
            $dates = explode(" - ", $this->date_range);

            $this->departure_date = strtotime($dates[0]);
            $this->return_date = strtotime($dates[1]);
        }
//        var_dump($this->date_range);
//        die;
        
    }
    
    public function setDateRange()
    {
        $this->date_range = date('Y-m-d', $this->departure_date) . " - " . date('Y-m-d', $this->return_date);
    }
    
    public function setReadableDateRange()
    {
        $this->departure_date = date('Y-m-d', $this->departure_date);
        $this->return_date = date('Y-m-d', $this->return_date);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'board_basis_id' => Yii::t('app', 'Board Basis ID'),
            'title' => Yii::t('app', 'Title'),
            'price' => Yii::t('app', 'Price'),
            'location' => Yii::t('app', 'Location'),
            'longitude' => Yii::t('app', 'Longitude'),
            'latitude' => Yii::t('app', 'Latitude'),
            'departure_date' => Yii::t('app', 'Departure Date'),
            'return_date' => Yii::t('app', 'Return Date'),
            'transfer' => Yii::t('app', 'Transfer'),
            'return_transfer' => Yii::t('app', 'Return Transfer'),
            'luggage_allowance' => Yii::t('app', 'Luggage Allowance'),
            'out_link' => Yii::t('app', 'Out Link'),
            'created_at' => Yii::t('app', 'Created At'),
            'status' => Yii::t('app', 'Status'),
            'description' => Yii::t('app', 'Description'),
        ];
    }
    
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'user_id',
                'updatedByAttribute' => false,
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBoardBasis()
    {
        return $this->hasOne(BoardBasis::className(), ['id' => 'board_basis_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPreference()
    {
        return $this->hasOne(Preference::className(), ['id' => 'preference_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOfferImages()
    {
        return $this->hasMany(OfferImage::className(), ['offer_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRooms()
    {
        return $this->hasMany(Room::className(), ['offer_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getThingsToDos()
    {
        return $this->hasMany(ThingsToDo::className(), ['offer_id' => 'id']);
    }
    
    public function getMainImageURL()
    {
        $images = $this->offerImages;
        if(isset($images[0])){
            $mainImage = $images[0];
            return $mainImage->getImageURL();
        }else{
            return null;
        }
    }
}

modules/supplier/controllers/OfferController.php
<?php

namespace app\modules\supplier\controllers;

use Yii;
use app\modules\supplier\models\Offer;
use app\modules\supplier\models\OfferSearch;
use app\modules\supplier\models\OfferImage;
use app\modules\supplier\models\OfferImageSearch;
use app\modules\supplier\models\Room;
use app\modules\supplier\models\RoomSearch;
use app\modules\supplier\models\ThingsToDo;
use app\modules\supplier\models\ThingsToDoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


/**
 * OfferController implements the CRUD actions for Offer model.
 */
class OfferController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'deleteOfferImage' => ['POST'],
                ],
            ],
        ];
    }
    
    public function actionNotify($email) {
    
        $result = \Yii::$app->mailer->compose(['html' => 'user-notification-html'],
                ['user' => \Yii::$app->user->identity, 'model' => $this])
                ->setFrom([\Yii::$app->params['supportEmail'] => \Yii::$app->name])
                ->setTo($email)
                ->setSubject('Your travel offers are ready! (Final Step of your participation)')
                ->send();
        if($result){
                Yii::$app->getSession()->setFlash('supplier',Yii::t('app','The notification was sent successfuly!'));
        }else{
                Yii::$app->getSession()->setFlash('supplier',Yii::t('app','Sending notification failed.'));
        }
        return $this->goBack();
    }
    

    /**
     * Lists all Offer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OfferSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Offer model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $offerImage = new OfferImage();
        if ($offerImage->load(Yii::$app->request->post())){
            $offerImage->imageFile = UploadedFile::getInstance($offerImage, 'imageFile');
            $offerImage->offer_id = $id;
            $offerImage->save();
        }
        
        $offerImageSearch = new OfferImageSearch();
        $offerImageDataProvider = $offerImageSearch->search(Yii::$app->request->queryParams,['offerId' => $id]);
        //
        
        $room = new Room();
        if ($room->load(Yii::$app->request->post()) ){
            $room->offer_id = $id;
            $room->save();
        }
        
        $roomSearch = new RoomSearch();
        $roomDataProvider = $roomSearch->search(Yii::$app->request->queryParams,['offerId' => $id]);
        
        ///
        $thingsToDo = new ThingsToDo();
        
        if ($thingsToDo->load(Yii::$app->request->post()) ){
            $thingsToDo->imageFile = UploadedFile::getInstance($thingsToDo, 'imageFile');
            $thingsToDo->offer_id = $id;
            $thingsToDo->setDates();
            $thingsToDo->save();
        }
        
        $thingsToDoSearch = new ThingsToDoSearch();
        $thingsToDoDataProvider = $thingsToDoSearch->search(Yii::$app->request->queryParams,['offerId' => $id]);
        
        return $this->render('view', [
            'model' => $this->findModel($id),
            'offerImage' => $offerImage,
            'offerImageDataProvider' => $offerImageDataProvider,
            'room' => $room,
            'roomDataProvider' => $roomDataProvider,
            'thingsToDo' => $thingsToDo,
            'thingsToDoDataProvider' => $thingsToDoDataProvider,
            
        ]);
    }
    
    public function actionDeleteOfferImage($id)
    {
        if (($model = OfferImage::findOne($id)) !== null) {
            $model->delete();
            $this->goBack();
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
    
    public function actionDeleteRoom($id){
        if (($model = Room::findOne($id)) !== null) {
            $model->delete();
            $this->goBack();
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    /**
     * Creates a new Offer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Offer();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Offer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->setReadableDateRange();
        
        if ($model->load(Yii::$app->request->post())) {
            
            $model->setDates();
            
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Offer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Offer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Offer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Offer::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/supplier/controllers/RoomController.php
<?php

namespace app\modules\supplier\controllers;

use Yii;
use app\modules\supplier\models\Room;
use app\modules\supplier\models\RoomSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RoomController implements the CRUD actions for Room model.
 */
class RoomController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Room models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RoomSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Room model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Room model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Room();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Room model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Room model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Room model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Room the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Room::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/supplier/views/offer/_form.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use kartik\widgets\ActiveForm;
use kartik\daterange\DateRangePicker;
/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\Offer */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="offer-form">

    <?php $form = ActiveForm::begin(); ?>

    

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'board_basis_id')->dropdownList(
            app\modules\admin\models\BoardBasis::find()->select(['title', 'id'])->indexBy('id')->column(),
            ['prompt'=>Yii::t('app','Select Board Basis')]
        );
    ?>
    <?php  
    if($model->isNewRecord){
       echo $form->field($model, 'date_range', [
            'addon'=>['prepend'=>['content'=>'<i class="glyphicon glyphicon-calendar"></i>']],
            'options'=>['class'=>'drp-container form-group']
        ])->widget(DateRangePicker::classname(), [
            'useWithAddon'=>true
        ]); 
    }else{
        echo '<label class="control-label" for="offer-date_range">Date Range</label>';
        echo DateRangePicker::widget([
            'model'=>$model,
            'attribute' => 'date_range',
            //'useWithAddon'=>true,
            'convertFormat'=>true,
            'startAttribute' => 'departure_date',
            'endAttribute' => 'return_date',
            'pluginOptions'=>[
                'locale'=>['format' => 'Y-m-d'],
            ]
        ]);
    }
   ?>
    

    <?= $form->field($model, 'location')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model,'description')->textarea() ?>

    <?= $form->field($model, 'longitude')->textInput() ?>

    <?= $form->field($model, 'latitude')->textInput() ?>

    


    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/supplier/views/offer/_messages.php
<?php
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
if(Yii::$app->session->hasFlash('supplier')){
    $this->registerJs("$('#user').modal();", $this::POS_END);
    
}

Modal::begin([
            'header' => Yii::t('app','Hola!'),
            'id' => 'user',
        ]);
        if(Yii::$app->session->hasFlash('supplier')){
            echo Html::tag('p',Yii::$app->session->getFlash('supplier'));
        }
        
Modal::end(); 

?>

modules/supplier/views/offer/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\OfferSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="offer-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'board_basis_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'location') ?>

    <?php // echo $form->field($model, 'longitude') ?>

    <?php // echo $form->field($model, 'latitude') ?>

    <?php // echo $form->field($model, 'departure_date') ?>

    <?php // echo $form->field($model, 'return_date') ?>

    <?php // echo $form->field($model, 'transfer') ?>

    <?php // echo $form->field($model, 'return_transfer') ?>

    <?php // echo $form->field($model, 'luggage_allowance') ?>

    <?php // echo $form->field($model, 'out_link') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/supplier/views/offer/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\Offer */

$this->title = Yii::t('app', 'Add Offer');
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Offers'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="offer-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/supplier/views/offer/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\modules\supplier\models\OfferSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Offers');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="offer-index">

    <h1><?= Html::encode($this->title) ?></h1>
    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'preference_id',
            [
                'attribute' => 'user_id',
                'content' => function($data){
                    return $data->user->username;
                }
            ],
            [
                'attribute' => 'board_basis_id',
                'content' => function($data){
                    return $data->boardBasis->title;
                }
            ],
            
            'title',
            'price:currency',
            //'location',
            //'longitude',
            //'latitude',
            //'departure_date',
            //'return_date',
            //'transfer',
            //'return_transfer',
            //'luggage_allowance',
            //'out_link',
            //'created_at',
            //'status',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}{update}{delete}',
                'buttons' => [
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                'title' => Yii::t('app', 'delete'),
                        ],['data-method' => 'post']);
                    },
                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                'title' => Yii::t('app', 'update'),
                        ]);
                    },
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                'title' => Yii::t('app', 'view'),
                        ]);
                    }
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'delete') {
                        $url = Url::to(['offer/delete','id' => $model->id]);
                        return $url;
                    }
                    if ($action === 'view') {
                        $url = Url::to(['offer/view','id' => $model->id]);
                        return $url;
                    }
                    if ($action === 'update') {
                        $url = Url::to(['offer/update','id' => $model->id]);
                        return $url;
                    }
                }
            ],
        ],
    ]); ?>
    
</div>

modules/supplier/views/offer/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\Offer */

$this->title = Yii::t('app', 'Update Offer: {nameAttribute}', [
    'nameAttribute' => $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Offers'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="offer-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/supplier/views/offer/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\supplier\models\Offer */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Offers'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="offer-view">

    
    <div class="col-md-6">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['offer/update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a(Yii::t('app', 'Send Notification To The User!'), ['offer/notify', 'email' => $model->preference->user->email], ['class' => 'btn btn-warning']) ?>
    </p>
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                [
                    'attribute' => 'user_id',
                    'value' => $model->user->username,
                ],
                
                'board_basis_id',
                'title',
                'price:currency',
                'location',
                'longitude',
                'latitude',
                'departure_date:date',
                'return_date:date',
                'transfer',
                'return_transfer',
                'luggage_allowance',
                'out_link',
                'created_at:datetime',
                'status',
            ],
        ]) ?>
        <h2>Preference Set</h2>
        <?= $this->render('/preference/_details',['model'=>$model->preference]) ?>
    </div>
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading"><h3>Images</h3></div>
            <div class="panel-body">
              <?= $this->render('/offerimage/create', ['model' => $offerImage]) ?>
                  <?= $this->render('/offerimage/index',['dataProvider' => $offerImageDataProvider]) ?>
            </div>
        </div>
        
        <div class="panel panel-info">
            <div class="panel-heading"><h3>Rooms</h3></div>
            <div class="panel-body">
              <?= $this->render('/room/create', ['model' => $room]) ?>
                  <?= $this->render('/room/index', ['dataProvider' => $roomDataProvider]) ?>
            </div>
        </div>
        
        <div class="panel panel-info">
            <div class="panel-heading"><h3>Things To Do</h3></div>
            <div class="panel-body">
              <?= $this->render('/thingstodo/create', ['model' => $thingsToDo]) ?>
              <?= $this->render('/thingstodo/index', ['dataProvider' => $thingsToDoDataProvider]) ?>
            </div>
        </div>
        
    </div>

</div>
<?= $this->render('_messages') ?>